sudo: false

dist: bionic

language: php

matrix:
  include:
    - php: 5.6
      env: AUTOLOAD=1
      dist: xenial
    - php: 5.6
      env: AUTOLOAD=0
      dist: xenial
    - php: 7.0
      env: AUTOLOAD=1
      dist: xenial
    - php: 7.0
      env: AUTOLOAD=0
      dist: xenial
    - php: 7.1
      env: AUTOLOAD=1
    - php: 7.1
      env: AUTOLOAD=0
    - php: 7.2
      env: AUTOLOAD=1
    - php: 7.2
      env: AUTOLOAD=0
    - php: 7.3
      env: AUTOLOAD=1
    - php: 7.3
      env: AUTOLOAD=0
    - php: 7.4
      env: AUTOLOAD=1
    - php: 7.4
      env: AUTOLOAD=0

env:
  global:
    - STRIPE_MOCK_VERSION=0.101.0
cache:
  directories:
    - $HOME/.composer/cache/files
    - epayco-mock

before_install:
  # Install various build dependencies. We use `travis_retry` because Composer
  # will occasionally fail intermittently.
  - travis_retry make vendor

  # Unpack and start epayco-mock so that the test suite can talk to it
  - |
    if [ ! -d "epayco-mock/epayco-mock_${STRIPE_MOCK_VERSION}" ]; then
      mkdir -p epayco-mock/epayco-mock_${STRIPE_MOCK_VERSION}/
      curl -L "https://github.com/epayco/epayco-mock/releases/download/v${STRIPE_MOCK_VERSION}/epayco-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -o "epayco-mock/epayco-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz"
      tar -zxf "epayco-mock/epayco-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -C "epayco-mock/epayco-mock_${STRIPE_MOCK_VERSION}/"
    fi
  - |
    epayco-mock/epayco-mock_${STRIPE_MOCK_VERSION}/epayco-mock > /dev/null &
    STRIPE_MOCK_PID=$!
  - export PATH="${PATH}:${PWD}/epayco-mock/epayco-mock_${STRIPE_MOCK_VERSION}"

script:
  - ./build.php ${AUTOLOAD}
  - make fmtcheck
  - if [[ `php -r "echo \version_compare(PHP_VERSION, '7.1', '>=');"` && $AUTOLOAD == 1 ]]; then make phpstan; fi

after_script: ./vendor/bin/php-coveralls -v
